.TH STRENGTH-CLI "1" "June 2016" "strength-cli 0.12"
.SH NAME
strength-cli \- a remote procedure call client for STRENGTH Core. 
.SH SYNOPSIS
strength-cli [options] <command> [params] \- Send command to STRENGTH Core. 
.TP
strength-cli [options] help \- Asks STRENGTH Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the strength-cli program. strength-cli is an RPC client used to send commands to STRENGTH Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBstrengthd\fP, \fBstrength.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
