#ifndef STRENGTH_CHAINPARAMSSEEDS_H
#define STRENGTH_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the strength network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xb3,0x2b,0x9d,0x3a}, 25010}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // STRENGTH_CHAINPARAMSSEEDS_H
